spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/bookcircle-db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

server:
  port: 8080

app:
  jwt:
    secret: "furew9doij2130jrj340r2ikeik23j9r04j9j1ir90ei3290e"
    accessTokenMinutes: 60
  h3:
    defaultResolution: 9

logging:
  level:
    root: INFO
    bookcircle: INFO
