name: Java CI

on:
  push:
    paths:
      - 'backend/**'
      - '.github/workflows/ci.yml'

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: ''
      - name: Build with Maven
        run: mvn clean install